### ISSUE TITLE
[Feature Request] Enable Use with Tidy 5e Sheet's "Favorite" items

### ISSUE THREAD

**Issue by timartiny** [trev33b/dice-tooltip2#1]
Found your repo from as a fork of the original, its great!

This module works with Tidy 5e Sheet if you go to the inventory tab/spellcasting tab etc. But if you favorite an item or a spell so it shows on the "front" page (Attributes) no tool tip shows up on hover.

EDIT: To clarify, this is for PCs. NPCs work as expected

Could that be added?

**Comment by trev33b** [comment]
Sorry for taking a while to reply.  I was waiting for the Foundry team to allow me to publish my module.  They were trying to get a response from the original owner I forked this from, but they appear to be MIA.  So, I'm now the owner of the module.

Your request sounds reasonable, I'll look into this.

**Comment by trev33b** [comment]
I've added support for showing tooltips on favorites in 2.1.0.  These were tricky to add because the DOM elements for the favorites are dynamically generated by Tidy5e.
