### ISSUE TITLE
Always Updating

### ISSUE THREAD

**Issue by infias** [trev33b/dice-tooltip2#12]
When updating, it always seems to think there's a need to reinstall the module. Possible v10 manifest issue?

![image](https://user-images.githubusercontent.com/88762169/199053069-db5010f3-c1dd-4c42-89d7-32ea7c1c339a.png)

**Comment by trev33b** [comment]
I've had a similar report.  Looks like it is a manifest issue as you suspect.  Working on it...

**Comment by trev33b** [comment]
Version 2.4.2 fixes the problem.  Turned out I was pointing to the old zip file which explains the behavior you were seeing.
