### ISSUE TITLE
Enhancement - Versatile Rolls

### ISSUE THREAD

**Issue by ravingdragoon** [trev33b/dice-tooltip2#5]
It would be awesome if the hover tooltip listed the versatile rolls in the D&D 5e system.

**Comment by trev33b** [comment]
It kind of does.  At the moment, it only shows one set of damage rolls and if versatile is available, it only shows that.  I suspect the original author figured you'd always want to use versatile if you had it....but it's not obvious that it's there.

I want to modify it to show both possible damage rolls and make it obvious which is which.   I'll leave this open to reflect that.

**Comment by trev33b** [comment]
Implemented in 2.2.0
