### ISSUE TITLE
Graphical Error with SmallTime Enabled

### ISSUE THREAD

**Issue by Brimcon** [trev33b/dice-tooltip2#6]
I'm not quite sure where to report this but with the Module SmallTime enabled I get this small graphical error.

![image](https://user-images.githubusercontent.com/7198283/152704815-2c79eb96-5dcd-4807-80e0-0349e7c1bed6.png)

Should I report this to SmallTime?

Foundry Version 9.249
D&D Version 1.5.7 
DiceTooltip version 2.0.1
SmallTime 1.13.13

**Comment by trev33b** [comment]
I'll see if I can reproduce this.  Probably a stylesheet conflict

**Comment by trev33b** [comment]
I've reproduced this issue by installing SmallTime

**Comment by trev33b** [comment]
I confirmed this was a stylesheet issue.  I have a fix for this which will be included in the next update.  I'll close this issue once I've released it.
