### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'hasSave') dicetooltip.js:239 

### ISSUE THREAD

**Issue by thatlonelybugbear** [trev33b/dice-tooltip2#9]
When using with other modules that deal with automation like MidiQOL, there are instances that the `item` will not be defined (like when an overtime effect is applied on an actor).

In such cases that error is triggered, as well as errors for `hasDamage` and `hasAttack`.

Might be good to plan for such cases with `item?.hasSave` etc instead of the more strict `item.hasSave`

**Comment by trev33b** [comment]
@thatlonelybugbear:

I have a fix for this in 2.3.1 which I've just released.  I didn't attempt to reproduce this myself, but the fix seemed obvious.  If you could verify that I've resolved this, that would be much appreciated.

Thanks!

**Comment by thatlonelybugbear** [comment]
I will done time later today. Cheers!!

**Comment by trev33b** [comment]
It's been a while, so I'm going to close this.  Will assume it works.  Please reopen if you see otherwise.
